# Generated by Django 4.2.6 on 2024-04-24 04:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopisy", "0002_customuser_delete_member"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
